version: "2"
services: 
  registry:
    restart: always
    image: registry:2
    container_name: docker_register
    ports:
      - 443:443
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:443
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/carter.me.crt
      REGISTRY_HTTP_TLS_KEY: /certs/carter.me.key
    volumes:
      - ~/data:/var/lib/registry
      - ~/certs:/certs
  registry-ui:
    restart: always
    image: quiq/docker-registry-ui
    container_name: docker_register_ui
    ports:
      - 8000:8000
    volumes:
      - ~/certs/carter.me.crt:/etc/ssl/certs/ca-certificates.crt:ro
      - ./config.yml:/opt/config.yml:ro
